-- Admin access via limited-use invite codes.
-- Replaces the hardcoded APPROVED_USER_IDS list in lib/supabase/client.ts.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  granted_by uuid null references auth.users (id) on delete set null,
  source text not null default 'invite', -- 'seed' | 'invite'
  created_at timestamptz not null default timezone('utc', now())
);

-- One invite code per user (enforced by unique owner_user_id), with a usage cap.
create table if not exists public.admin_invite_codes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null unique references auth.users (id) on delete cascade,
  code text not null unique,
  max_uses integer not null default 1,
  uses_count integer not null default 0,
  revoked boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

-- Ledger of redemptions; unique redeemed_by prevents a user from redeeming twice.
create table if not exists public.admin_invite_redemptions (
  id bigint generated by default as identity primary key,
  code_id bigint not null references public.admin_invite_codes (id) on delete cascade,
  redeemed_by uuid not null unique references auth.users (id) on delete cascade,
  redeemed_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_invite_redemptions_code_id_idx
  on public.admin_invite_redemptions (code_id);

-- Exposes only validity, so anonymous invite visitors do not need table access.
create or replace function public.get_admin_invite_code_status(p_code text)
returns table (is_valid boolean)
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_invite_codes
    where code = upper(trim(p_code))
      and not revoked
      and uses_count < max_uses
  );
$$;

grant execute on function public.get_admin_invite_code_status(text) to anon, authenticated;

-- Atomically checks the usage cap and increments it, so concurrent signups
-- can't both redeem a code once only one use remains.
create or replace function public.redeem_admin_invite_code(p_code text, p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code_id bigint;
  v_owner uuid;
begin
  if p_code is null or length(trim(p_code)) = 0 then
    return false;
  end if;

  update public.admin_invite_codes
  set uses_count = uses_count + 1
  where code = p_code
    and not revoked
    and uses_count < max_uses
  returning id, owner_user_id into v_code_id, v_owner;

  if v_code_id is null then
    return false;
  end if;

  insert into public.admin_invite_redemptions (code_id, redeemed_by)
  values (v_code_id, p_user_id)
  on conflict (redeemed_by) do nothing;

  insert into public.admin_users (user_id, granted_by, source)
  values (p_user_id, v_owner, 'invite')
  on conflict (user_id) do nothing;

  return true;
end;
$$;

alter table public.admin_users enable row level security;
alter table public.admin_invite_codes enable row level security;
alter table public.admin_invite_redemptions enable row level security;

grant select on public.admin_users to authenticated;
grant select, insert on public.admin_invite_codes to authenticated;
grant execute on function public.redeem_admin_invite_code(text, uuid) to authenticated;

drop policy if exists "Admins can read the admin list" on public.admin_users;
create policy "Admins can read the admin list"
on public.admin_users
for select
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

drop policy if exists "Admins can read their own invite code" on public.admin_invite_codes;
create policy "Admins can read their own invite code"
on public.admin_invite_codes
for select
to authenticated
using (owner_user_id = auth.uid());

drop policy if exists "Admins can create their own invite code" on public.admin_invite_codes;
create policy "Admins can create their own invite code"
on public.admin_invite_codes
for insert
to authenticated
with check (
  owner_user_id = auth.uid()
  and exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

-- Allow admins to moderate (delete) any review, not just their own.
drop policy if exists "Admins can delete any review" on public."Reviews";
create policy "Admins can delete any review"
on public."Reviews"
for delete
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

-- Seed the pre-existing hardcoded admin ids so access isn't lost during migration.
insert into public.admin_users (user_id, source)
values
  ('ba398812-06a0-4c48-9f15-0660d3af0047', 'seed'),
  ('f2694e1c-5457-45b0-b299-c3a03a77d8c5', 'seed'),
  ('e8191ca7-7856-4e81-9140-b93a944ec711', 'seed')
on conflict (user_id) do nothing;

-- Credits an admin's own invite code with one use when a Google Calendar event
-- they created is approved during manual review.
create or replace function public.increment_admin_invite_code_usage(p_owner_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code_id bigint;
begin
  update public.admin_invite_codes
  set uses_count = uses_count + 1
  where owner_user_id = p_owner_user_id
    and not revoked
  returning id into v_code_id;

  return v_code_id is not null;
end;
$$;

grant execute on function public.increment_admin_invite_code_usage(uuid) to authenticated, service_role;
