-- Tracks when a user's device location has been confirmed at an event they RSVP'ed to,
-- so we only send one location-confirmation push notification per user/event.
create table if not exists public.location_confirmations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  event_id bigint not null,
  latitude double precision not null,
  longitude double precision not null,
  distance_meters integer null,
  confirmed_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_id)
);

create index if not exists location_confirmations_user_id_idx
  on public.location_confirmations (user_id);

alter table public.location_confirmations enable row level security;

grant select, insert on public.location_confirmations to authenticated;
grant usage, select on sequence public.location_confirmations_id_seq to authenticated;

drop policy if exists "Users can read their own location confirmations" on public.location_confirmations;
create policy "Users can read their own location confirmations"
on public.location_confirmations
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own location confirmations" on public.location_confirmations;
create policy "Users can insert their own location confirmations"
on public.location_confirmations
for insert
with check (auth.uid() = user_id);
