-- Threaded comments under a review. Each reply belongs to a review, and may
-- optionally belong to another reply (for nested replies).
create table if not exists public.review_replies (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public."Reviews" (id) on delete cascade,
  parent_reply_id bigint null references public.review_replies (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  comment text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists review_replies_review_id_idx on public.review_replies (review_id);
create index if not exists review_replies_parent_reply_id_idx on public.review_replies (parent_reply_id);

alter table public.review_replies enable row level security;

grant select on public.review_replies to anon, authenticated;
grant insert, delete on public.review_replies to authenticated;

drop policy if exists "Anyone can read review replies" on public.review_replies;
create policy "Anyone can read review replies"
on public.review_replies
for select
to anon, authenticated
using (true);

drop policy if exists "Users can add their own replies" on public.review_replies;
create policy "Users can add their own replies"
on public.review_replies
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can delete their own replies" on public.review_replies;
create policy "Users can delete their own replies"
on public.review_replies
for delete
to authenticated
using (user_id = auth.uid());
