-- Create shareable user party plans
create table if not exists public.user_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_name text not null default '',
  event_ids int8[] not null
);

-- If the table already exists without id, backfill a dedicated identity id.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'user_plans' and column_name = 'id'
  ) then
    alter table public.user_plans add column id bigint generated by default as identity;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'user_plans' and column_name = 'plan_name'
  ) then
    alter table public.user_plans add column plan_name text not null default '';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.user_plans'::regclass and contype = 'p'
  ) then
    alter table public.user_plans add primary key (id);
  end if;
end
$$;

alter table public.user_plans enable row level security;

-- Users can create and view only their own plans.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_plans' and policyname = 'user_plans_select_own'
  ) then
    create policy user_plans_select_own
      on public.user_plans
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_plans' and policyname = 'user_plans_insert_own'
  ) then
    create policy user_plans_insert_own
      on public.user_plans
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_plans' and policyname = 'user_plans_update_own'
  ) then
    create policy user_plans_update_own
      on public.user_plans
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'user_plans' and policyname = 'user_plans_delete_own'
  ) then
    create policy user_plans_delete_own
      on public.user_plans
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end
$$;
